export { default as AddUser } from "./AddUser";
export { default as Analytics } from "./Analytics";
export { default as Customers } from "./Customers";
export { default as Dashboard } from "./Dashboard";
export { default as EditContact } from "./EditContact";
export { default as EditStaff } from "./EditStaff";
export { default as EditUser } from "./EditUser";
export { default as EditPackage } from "./EditPackage";
export { default as Evaluation } from "./Evaluation";
// export { default as Evaluations } from "./Evaluations";
export { default as Packages } from "./Packages";
// export { default as Feedbacks } from "./Feedbacks";
export { default as Inventory } from "./Inventory";
export { default as Staffs } from "./Staffs";
export { default as Profile } from "./Profile";
export { default as Login } from "./Login";
export { default as Settings } from "./Settings";
export { default as Orders } from "./Orders";
export { default as ManageOrder } from "./ManageOrder";
export { default as SignUp } from "./signup/index";
export { default as SignIn } from "./signin/index";
export { default as PassReset } from "./passreset/index";
